---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: router
  namespace: router
spec:
  interval: 3m0s
  ref:
    branch: master
  secretRef:
    name: router
  url: ssh://git@github.com/awzmb/flux-router-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: router
  namespace: router
spec:
  interval: 10m0s
  path: ./prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: router
  validation: client
